### ISSUE TITLE
sysmon.service won't start because of libbpf issue

### ISSUE THREAD

**Issue by luffynextgen** [Sysinternals/SysmonForLinux#66]
### OS and Sysmon version Info

CentOS 8.2.2004
Kernel Version 4.18.0-193.19.1.el8_2.x86_64
sysmonforlinux-1.0.2-1.x86_64
packages-microsoft-prod-1.0.1.noarch

### Error printed
When using `sysmon -accepteula -i`
- `Job for sysmon.service failed because the control process exited with error code`
- Details in service status:

<img width="552" alt="sysmon_service_details" src="https://user-images.githubusercontent.com/34096485/162958300-081dc4eb-2c67-4b1e-b186-dc2c041a0cf7.png">

The issue seems to come from sysinternalsEPBF.
The package was downloaded from the yum repository.

### Note

sysmonforlinux works well on CentOS 8.1.1911 (Core) with kernel 4.18.0-147.5.1.el8_1.x86_64
**EDIT:**
 I tried to restart the sysmon service on the server it was working, and now it won't restart:

       1. first the error I had was about  libsysinternalsEBPF.so that was not found, I had to recompile it to solve this issue
       2. Once the library was recompiled and found, now sysmon can't find sysinternalsEBPFrawSock.o program
       sysinternalsEBPFrawSock.o program is well located in  /opt/sysinternalsEBPF/ but sysmon can't find it:
       
       Apr 12 16:18:32 server01 sysmon[222692]: Using EBPF object: .//sysmonEBPFkern4.17-5.1.o
       Apr 12 16:18:34 server01 sysmon[222692]: ERROR: failed to locate program: /opt/sysinternalsEBPF/sysinternalsEBPFrawSock.o 'Invalid argument'
       Apr 12 16:18:34 server01 sysmon[222692]: ERROR: failed to enable raw socket capture
       Apr 12 16:18:34 server01 sysmon[222692]: Telemetry failed to start: Raw socket program could not be attached

**Comment by anforcer** [comment]
Almost same thing with Debian OS - sysmon service doesnt start.
My specification:

**Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-20-amd64
Architecture: x86-64**

sysmon accepteula error:

`
root@debian:~|⇒  sudo sysmon -accepteula -i /opt/config.xml

Sysmon v1.0.2 - Monitors system events
Sysinternals - www.sysinternals.com
By Mark Russinovich, Thomas Garnier and Kevin Sheldrake
Copyright (C) 2014-2021 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.

Loading configuration file with schema version 4.81
Configuration file validated.
Job for sysmon.service failed because the control process exited with error code.
See "systemctl status sysmon.service" and "journalctl -xe" for details.
`
sysmon service status error:
`
root@debian:~|⇒  systemctl status sysmon.service
● sysmon.service - Sysmon event logger
   Loaded: loaded (/etc/systemd/system/sysmon.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-04-14 13:29:38 EDT; 6s ago
  Process: 1224 ExecStart=/opt/sysmon/sysmon -i /opt/sysmon/config.xml -service (code=exited, status=12)

Apr 14 13:29:38 debian sysmon[1224]: 1705: (79) r1 = *(u64 *)(r10 -128)
Apr 14 13:29:38 debian sysmon[1224]: 1706: (a7) r1 ^= 4095
Apr 14 13:29:38 debian sysmon[1224]: 1707: (79) r2 = *(u64 *)(r10 -96)
Apr 14 13:29:38 debian sysmon[1224]: 1708: (0f) r2 += r1
Apr 14 13:29:38 debian sysmon[1224]: math between map_value pointer and register with unbounded min value is not allowed
Apr 14 13:29:38 debian sysmon[1224]: libbpf: -- END LOG --
Apr 14 13:29:38 debian sysmon[1224]: libbpf: failed to load program 'sysmon/ProcCreate/rawExit'
Apr 14 13:29:38 debian sysmon[1224]: libbpf: failed to load object './/sysmonEBPFkern4.17-5.1.o'
Apr 14 13:29:38 debian sysmon[1224]: ERROR: failed to load prog: 'Invalid argument'
Apr 14 13:29:38 debian sysmon[1224]: Telemetry failed to start: eBPF object could not be loaded
`

**Comment by luffynextgen** [comment]
On the CentOS server 8.1.1911 (Core) with kernel 4.18.0-147.5.1.el8_1.x86_64, I update sysmon to version 1.0.2-1
This updates give the same math issue as the one on the CentOS 8.2.2004 Server or by @anforcer with the Debian server.
<img width="864" alt="image" src="https://user-images.githubusercontent.com/34096485/165255153-41a0b21d-0c26-47b2-bb79-274e0a6318a3.png">

Kind regards,

**Comment by raomin** [comment]
Hi @kesheldr,
Sorry for the direct tagging... Can you provide some hints for solving this issue?
Thanks in advance!

**Comment by MarioHewardt** [comment]
It looks like the verifier is having problems verifying the eBPF program. We'll add this to our backlog to look into.

**Comment by BDH-Granicus** [comment]
Thanks @MarioHewardt

**Comment by raomin** [comment]
Hello @MarioHewardt, this is still preventing us from deploying Sysmon on our linux servers. Would you have an idea on when we can expect a solution? Thanks!

**Comment by MarioHewardt** [comment]
I'm still working on some other work items. I will update everyone as soon as I know more. Thanks for the patience.

**Comment by MarioHewardt** [comment]
Closing as I've pushed a fix that should resolve the issue. If you encounter it again, please reopen. You may have to run getOffsets (https://github.com/Sysinternals/SysinternalsEBPF/tree/main/getOffsets) to get this to work on CentOS8.

Please note that you will have to build Sysmon until we get new packages out.
